# Generated by Django 4.0.4 on 2022-06-04 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Train ID')),
                ('train_source', models.CharField(choices=[('None', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='None', max_length=20, verbose_name='Train Source')),
                ('train_destination', models.CharField(choices=[('None', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='None', max_length=20, verbose_name='Train Destination')),
                ('train_time', models.TimeField(verbose_name='Train Time')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Ticket ID')),
                ('ticket_source', models.CharField(choices=[('None', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='None', max_length=20, verbose_name='Ticket Source')),
                ('ticket_destination', models.CharField(choices=[('None', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='None', max_length=20, verbose_name='Ticket Destination')),
                ('ticket_type', models.CharField(choices=[('Journey', 'Journey'), ('Single', 'Single')], default='None', max_length=20, verbose_name='Ticket Type')),
                ('ticket_class', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='None', max_length=20, verbose_name='Ticket Class')),
                ('ticket_train', models.CharField(choices=[('Ordinary', 'Ordinary'), ('Air Conditioned', 'Air Conditioned')], default='None', max_length=20, verbose_name='Ticket Train')),
                ('ticket_payment', models.CharField(choices=[('Payment Gateway', 'Payment Gateway'), ('R Wallet', 'R Wallet')], default='None', max_length=20, verbose_name='Ticket Payment Method')),
                ('ticket_booked_at', models.DateTimeField(auto_now_add=True, verbose_name='Ticket Booked at')),
                ('ticket_fare', models.SmallIntegerField(default=0, verbose_name='Ticket Fare')),
                ('ticket_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ticket_Holder', to=settings.AUTH_USER_MODEL, verbose_name='Ticket Holder')),
            ],
        ),
    ]
