# Generated by Django 4.0.4 on 2022-06-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_train_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=20, null=True, verbose_name='City'),
        ),
    ]
