# Generated by Django 4.0.4 on 2022-06-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Login'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_destination',
            field=models.CharField(choices=[('None', 'None'), ('Virar', 'Virar'), ('Nallasopara', 'Nallasopara'), ('Vasai Road', 'Vasai Road'), ('Naigaon', 'Naigaon'), ('Bhayandar', 'Bhayandar'), ('Mira Road', 'Mira Road'), ('Dahisar', 'Dahisar'), ('Borivali', 'Borivali'), ('Kandivali', 'Kandivali'), ('Malad', 'Malad'), ('Goregaon', 'Goregaon'), ('Ram Mandir', 'Ram Mandir'), ('Jogeshwari', 'Jogeshwari'), ('Andheri', 'Andheri'), ('Vile Parle', 'Vile Parle'), ('Santacruz', 'Santacruz'), ('Khar Road', 'Khar Road'), ('Bandra', 'Bandra'), ('Mahim Junction', 'Mahim Junction'), ('Matunga Road', 'Matunga Road'), ('Dadar', 'Dadar'), ('Prabhadevi', 'Prabhadevi'), ('Lower Parel', 'Lower Parel'), ('Mahalaxmi', 'Mahalaxmi'), ('Mumbai Central', 'Mumbai Central'), ('Grant Road', 'Grant Road'), ('Charni Road', 'Charni Road'), ('Marine Lines', 'Marine Lines'), ('Churchgate', 'Churchgate')], default='None', max_length=20, verbose_name='Ticket Destination'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_source',
            field=models.CharField(choices=[('None', 'None'), ('Virar', 'Virar'), ('Nallasopara', 'Nallasopara'), ('Vasai Road', 'Vasai Road'), ('Naigaon', 'Naigaon'), ('Bhayandar', 'Bhayandar'), ('Mira Road', 'Mira Road'), ('Dahisar', 'Dahisar'), ('Borivali', 'Borivali'), ('Kandivali', 'Kandivali'), ('Malad', 'Malad'), ('Goregaon', 'Goregaon'), ('Ram Mandir', 'Ram Mandir'), ('Jogeshwari', 'Jogeshwari'), ('Andheri', 'Andheri'), ('Vile Parle', 'Vile Parle'), ('Santacruz', 'Santacruz'), ('Khar Road', 'Khar Road'), ('Bandra', 'Bandra'), ('Mahim Junction', 'Mahim Junction'), ('Matunga Road', 'Matunga Road'), ('Dadar', 'Dadar'), ('Prabhadevi', 'Prabhadevi'), ('Lower Parel', 'Lower Parel'), ('Mahalaxmi', 'Mahalaxmi'), ('Mumbai Central', 'Mumbai Central'), ('Grant Road', 'Grant Road'), ('Charni Road', 'Charni Road'), ('Marine Lines', 'Marine Lines'), ('Churchgate', 'Churchgate')], default='None', max_length=20, verbose_name='Ticket Source'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_train',
            field=models.CharField(choices=[('ORD', 'Ordinary'), ('AC', 'Air Conditioned')], default='None', max_length=20, verbose_name='Ticket Train'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Return', 'Return')], default='None', max_length=20, verbose_name='Ticket Type'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_destination',
            field=models.CharField(choices=[('None', 'None'), ('Virar', 'Virar'), ('Nallasopara', 'Nallasopara'), ('Vasai Road', 'Vasai Road'), ('Naigaon', 'Naigaon'), ('Bhayandar', 'Bhayandar'), ('Mira Road', 'Mira Road'), ('Dahisar', 'Dahisar'), ('Borivali', 'Borivali'), ('Kandivali', 'Kandivali'), ('Malad', 'Malad'), ('Goregaon', 'Goregaon'), ('Ram Mandir', 'Ram Mandir'), ('Jogeshwari', 'Jogeshwari'), ('Andheri', 'Andheri'), ('Vile Parle', 'Vile Parle'), ('Santacruz', 'Santacruz'), ('Khar Road', 'Khar Road'), ('Bandra', 'Bandra'), ('Mahim Junction', 'Mahim Junction'), ('Matunga Road', 'Matunga Road'), ('Dadar', 'Dadar'), ('Prabhadevi', 'Prabhadevi'), ('Lower Parel', 'Lower Parel'), ('Mahalaxmi', 'Mahalaxmi'), ('Mumbai Central', 'Mumbai Central'), ('Grant Road', 'Grant Road'), ('Charni Road', 'Charni Road'), ('Marine Lines', 'Marine Lines'), ('Churchgate', 'Churchgate')], default='None', max_length=20, verbose_name='Train Destination'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_source',
            field=models.CharField(choices=[('None', 'None'), ('Virar', 'Virar'), ('Nallasopara', 'Nallasopara'), ('Vasai Road', 'Vasai Road'), ('Naigaon', 'Naigaon'), ('Bhayandar', 'Bhayandar'), ('Mira Road', 'Mira Road'), ('Dahisar', 'Dahisar'), ('Borivali', 'Borivali'), ('Kandivali', 'Kandivali'), ('Malad', 'Malad'), ('Goregaon', 'Goregaon'), ('Ram Mandir', 'Ram Mandir'), ('Jogeshwari', 'Jogeshwari'), ('Andheri', 'Andheri'), ('Vile Parle', 'Vile Parle'), ('Santacruz', 'Santacruz'), ('Khar Road', 'Khar Road'), ('Bandra', 'Bandra'), ('Mahim Junction', 'Mahim Junction'), ('Matunga Road', 'Matunga Road'), ('Dadar', 'Dadar'), ('Prabhadevi', 'Prabhadevi'), ('Lower Parel', 'Lower Parel'), ('Mahalaxmi', 'Mahalaxmi'), ('Mumbai Central', 'Mumbai Central'), ('Grant Road', 'Grant Road'), ('Charni Road', 'Charni Road'), ('Marine Lines', 'Marine Lines'), ('Churchgate', 'Churchgate')], default='None', max_length=20, verbose_name='Train Source'),
        ),
    ]
